### ISSUE TITLE
project

### ISSUE THREAD

**Issue by tejareddy97** [je-suis-tm/graph-theory#30]
hi using sir model can u able to find the impact of superspreaders how the infection is spreading on random networks u can mail me reagarding that on gsreddy2297@gmail.com

**Comment by je-suis-tm** [comment]
Hi, in terms of impact, could you be a bit more specific? Do you refer to temporal impact on sir model? Also superspreaders change the topological structure of random networks. A power-law distribution could be considered as a network model where superspreaders (a vertex with extremely high degree) exist. The comparison between Erdos-Renyi and Barabasi-Albert is included in the project. You can get the "impact" from the comparison.

**Comment by tejareddy97** [comment]
Like if there is one person as superspreader then how the disease is
spreading from him to the people he is in close contact and from them how
it's spreading

**Comment by tejareddy97** [comment]
If one person in the network is a superspreader then how he is spreading to
its neighbours and also we will be changing the probability of the
connection so that the connections will be less

**Comment by je-suis-tm** [comment]
I am not sure if you are familiar with the concept of power law distribution. Basically a superspreader is a vertex with high degree and it can be modelled in Barabási–Albert model. A superspreader is at the right tail of degree distribution. To evaluate the individual vertex, I am afraid you have to use degree-based approximation or pair approximation and it will be very computationally expensive. In terms of changing the probability of the connections, it's only a matter of tweaking the hyperparameters. In our BA model, you can modify the upper limit of maximum degree and the lower limit of minimum degree.
